/**
 * Markdown Formatter for Loggy Chrome Extension
 * Exports captured console and network data as structured Markdown
 */

import type { ConsoleMessage } from '../types/console'
import type { HAREntry } from '../types/har'
import { consolidateNetworkEntries } from './consolidation-network'
import {
  bySeverityThenCount,
  consolidateConsoleLogs,
  formatConsoleLog,
  formatTimestampRange,
  isLikelyFailureSignal,
} from './formatter-console'
import { formatConsolidatedNetworkEntry, formatNetworkEntry } from './formatter-network'
import { escapeMarkdown, formatBytes, truncate } from './formatter-strings'

/**
 * Complete export data structure for Markdown generation
 */
export interface ExportData {
  /** URL of the inspected page */
  url: string
  /** ISO 8601 timestamp of capture */
  timestamp: string
  /** Whether to include context for coding agents/LLMs */
  includeAgentContext?: boolean
  /** Whether to include response body content in network entries */
  includeResponseBodies?: boolean
  /** Whether to truncate console log messages (default: true) */
  truncateConsoleLogs?: boolean
  /** Whether to deduplicate identical API calls in the export */
  deduplicateApiCalls?: boolean
  /** Captured console messages */
  consoleLogs: ConsoleMessage[]
  /** Captured network HAR entries */
  networkEntries: HAREntry[]
}

export { formatBytes, truncate }

/**
 * Formats complete export data as structured Markdown document
 * @param data - Export data containing console logs and network entries
 * @returns Formatted Markdown string
 */
export function formatMarkdown(data: ExportData): string {
  let output = ''
  const consolidatedLogs = consolidateConsoleLogs(data.consoleLogs).sort(bySeverityThenCount)
  const repeatedLogCount = data.consoleLogs.length - consolidatedLogs.length
  const failureSignals = consolidatedLogs.filter(isLikelyFailureSignal).slice(0, 10)
  const levelCount = data.consoleLogs.reduce(
    (acc, log) => {
      acc[log.level] += 1
      return acc
    },
    { error: 0, warn: 0, log: 0, info: 0, debug: 0 } as Record<ConsoleMessage['level'], number>
  )
  const consolidatedLevelCount = consolidatedLogs.reduce(
    (acc, log) => {
      acc[log.level] += 1
      return acc
    },
    { error: 0, warn: 0, log: 0, info: 0, debug: 0 } as Record<ConsoleMessage['level'], number>
  )

  // Header
  output += `## Debug Log Export\n\n`

  if (data.includeAgentContext) {
    output += `### LLM Guidance\n\n`
    output += `- This output is generated by Loggy, a Chrome DevTools extension for debugging web pages.\n`
    output += `- It captures browser console events and network requests from the inspected tab.\n`
    output += `- Start with **Debug Signals**, then correlate with **Console Logs** and **Network Requests** to find root causes.\n`
    output += `- Use URL, timestamps, and request metadata to map issues to failing user flows.\n\n`
  }

  // Environment Section
  output += `### Environment\n\n`
  output += `- **URL**: ${escapeMarkdown(data.url)}\n`
  output += `- **Timestamp**: ${data.timestamp}\n`
  output += `- **Console Logs**: ${data.consoleLogs.length}\n`
  output += `- **Unique Console Events**: ${consolidatedLogs.length}\n`
  output += `- **Consolidated Repeats**: ${repeatedLogCount}\n`
  output += `- **Network Requests**: ${data.networkEntries.length}\n\n`

  output += `### Debug Signals\n\n`
  output += `- **Errors (raw/consolidated)**: ${levelCount.error}/${consolidatedLevelCount.error}\n`
  output += `- **Warnings (raw/consolidated)**: ${levelCount.warn}/${consolidatedLevelCount.warn}\n`
  output += `- **Failure-Likely Events**: ${failureSignals.length}\n\n`

  if (failureSignals.length > 0) {
    const shouldTruncate = data.truncateConsoleLogs ?? true
    failureSignals.forEach((signal) => {
      const message = shouldTruncate ? truncate(signal.message, 320) : signal.message
      output += `- [${signal.level}] (${signal.count}x) ${formatTimestampRange(signal)} - ${escapeMarkdown(message)}\n`
    })
    output += '\n'
  }

  // Console Logs Section
  if (consolidatedLogs.length > 0) {
    output += `### Console Logs\n\n`
    output += `| First Seen | Last Seen | Level | Count | Message |\n`
    output += `|------------|-----------|-------|-------|---------|\n`
    const shouldTruncate = data.truncateConsoleLogs ?? true
    consolidatedLogs.forEach((log) => {
      output += `${formatConsoleLog(log, shouldTruncate)}\n`
    })
    output += '\n'
  } else {
    output += `### Console Logs\n\nNo console logs captured.\n\n`
  }

  // Network Requests Section
  if (data.networkEntries.length > 0) {
    if (data.deduplicateApiCalls) {
      const consolidated = consolidateNetworkEntries(data.networkEntries)
      output += `### Network Requests\n\n`
      output += `- **Unique Routes**: ${consolidated.length} (from ${data.networkEntries.length} total)\n\n`
      consolidated.forEach((group) => {
        output += formatConsolidatedNetworkEntry(group, {
          includeResponseBodies: data.includeResponseBodies ?? false,
        })
        output += '---\n\n'
      })
    } else {
      output += `### Network Requests\n\n`
      data.networkEntries.forEach((entry) => {
        output += formatNetworkEntry(entry, {
          includeResponseBodies: data.includeResponseBodies ?? false,
        })
        output += '---\n\n'
      })
    }
  } else {
    output += `### Network Requests\n\nNo network requests captured.\n\n`
  }

  return output
}
