/**
 * Markdown Formatter for Loggy Chrome Extension
 * Exports captured console and network data as structured Markdown
 */

import type { ConsoleMessage } from '../types/console'
import type { HAREntry } from '../types/har'
import type { ConsolidatedLog } from './consolidation'
import type { ConsolidatedNetworkEntry } from './consolidation-network'
import { consolidateNetworkEntries } from './consolidation-network'
import type { DebugEntry } from './debug-logger'
import { computeElevatedUrlPaths } from './elevated-paths'
import {
  bySeverityThenCount,
  consolidateConsoleLogs,
  formatConsoleLog,
  formatNetworkFailureSignals,
  formatTimestampRange,
  isLikelyFailureSignal,
} from './formatter-console'
import { formatConsolidatedNetworkEntry, formatNetworkEntry } from './formatter-network'
import { escapeMarkdown, formatBytes, truncate, truncateJSON } from './formatter-strings'

/**
 * Complete export data structure for Markdown generation
 */
export interface ExportData {
  /** URL of the inspected page */
  url: string
  /** ISO 8601 timestamp of capture */
  timestamp: string
  /** Whether to include context for coding agents/LLMs */
  includeAgentContext?: boolean
  /** Whether to include response body content in network entries */
  includeResponseBodies?: boolean
  /** Whether to truncate console log messages (default: true) */
  truncateConsoleLogs?: boolean
  /** Response body output mode: 'smart' (elide non-elevated bodies) or 'full' (default: 'smart') */
  responseBodyMode?: 'smart' | 'full'
  /** Whether to deduplicate identical API calls in the export */
  deduplicateApiCalls?: boolean
  /** Captured console messages */
  consoleLogs: ConsoleMessage[]
  /** Captured network HAR entries */
  networkEntries: HAREntry[]
  /** Optional debug log entries (only present in debug builds) */
  debugEntries?: DebugEntry[]
}

export { formatBytes, truncate, truncateJSON }

/**
 * Formats complete export data as structured Markdown document
 * @param data - Export data containing console logs and network entries
 * @returns Formatted Markdown string
 */
export function formatMarkdown(data: ExportData): string {
  const consolidatedLogs = consolidateConsoleLogs(data.consoleLogs).sort(bySeverityThenCount)
  const repeatedLogCount = data.consoleLogs.length - consolidatedLogs.length
  const failureSignals = consolidatedLogs.filter(isLikelyFailureSignal).slice(0, 10)
  const levelCount = data.consoleLogs.reduce(
    (acc, log) => {
      acc[log.level] += 1
      return acc
    },
    { error: 0, warn: 0, log: 0, info: 0, debug: 0 } as Record<ConsoleMessage['level'], number>
  )
  const consolidatedLevelCount = consolidatedLogs.reduce(
    (acc, log) => {
      acc[log.level] += 1
      return acc
    },
    { error: 0, warn: 0, log: 0, info: 0, debug: 0 } as Record<ConsoleMessage['level'], number>
  )

  // Session anchor = earliest observed timestamp across console + network.
  // Computed once at the top so every offset downstream is relative to the
  // same instant. Threads through `formatConsoleSection` and
  // `formatNetworkSection` to the per-entry formatters.
  const anchor = computeAnchor(data)

  return (
    formatHeaderSection(data) +
    formatEnvironmentSection(data, consolidatedLogs.length, repeatedLogCount) +
    formatDebugSignalsSection(data, failureSignals, levelCount, consolidatedLevelCount) +
    formatConsoleSection(data, consolidatedLogs, anchor) +
    formatNetworkSection(data, anchor) +
    formatDebugSection(data)
  )
}

/**
 * Computes the earliest observed timestamp across all console logs and
 * network entries. Returns `undefined` when no parseable timestamps are
 * available — callers must then render ISO timestamps only (no offset).
 */
function computeAnchor(data: ExportData): number | undefined {
  const candidates: string[] = []
  for (const log of data.consoleLogs) {
    if (log.timestamp) candidates.push(log.timestamp)
  }
  for (const entry of data.networkEntries) {
    if (entry.startedDateTime) candidates.push(entry.startedDateTime)
  }
  const validMs = candidates.map((t) => Date.parse(t)).filter((n) => !Number.isNaN(n))
  if (validMs.length === 0) return undefined
  return Math.min(...validMs)
}

function formatHeaderSection(data: ExportData): string {
  let output = `## Debug Log Export\n\n`
  if (data.includeAgentContext) {
    output += `### LLM Guidance\n\n`
    output += `- This output is generated by Loggy, a Chrome DevTools extension for debugging web pages.\n`
    output += `- It captures browser console events and network requests from the inspected tab.\n`
    output += `- Start with **Debug Signals**, then correlate with **Console Logs** and **Network Requests** to find root causes.\n`
    output += `- Use URL, timestamps, and request metadata to map issues to failing user flows.\n\n`
  }
  return output
}

function formatEnvironmentSection(
  data: ExportData,
  uniqueCount: number,
  repeatedCount: number
): string {
  let output = `### Environment\n\n`
  output += `- **URL**: ${escapeMarkdown(data.url)}\n`
  output += `- **Timestamp**: ${data.timestamp}\n`
  output += `- **Console Logs**: ${data.consoleLogs.length}\n`
  output += `- **Unique Console Events**: ${uniqueCount}\n`
  output += `- **Consolidated Repeats**: ${repeatedCount}\n`
  output += `- **Network Requests**: ${data.networkEntries.length}\n\n`
  return output
}

function formatDebugSignalsSection(
  data: ExportData,
  failureSignals: ConsolidatedLog[],
  levelCount: Record<ConsoleMessage['level'], number>,
  consolidatedLevelCount: Record<ConsoleMessage['level'], number>
): string {
  let output = `### Debug Signals\n\n`
  output += `- **Errors (raw/consolidated)**: ${levelCount.error}/${consolidatedLevelCount.error}\n`
  output += `- **Warnings (raw/consolidated)**: ${levelCount.warn}/${consolidatedLevelCount.warn}\n`
  output += formatNetworkFailureSignals(data.networkEntries)
  output += `- **Failure-Likely Events**: ${failureSignals.length}\n\n`

  if (failureSignals.length > 0) {
    const shouldTruncate = data.truncateConsoleLogs ?? true
    failureSignals.forEach((signal) => {
      const message = shouldTruncate ? truncate(signal.message, 320) : signal.message
      output += `- [${signal.level}] (${signal.count}x) ${formatTimestampRange(signal)} - ${escapeMarkdown(message)}\n`
    })
    output += '\n'
  }

  return output
}

function formatConsoleSection(
  data: ExportData,
  consolidatedLogs: ConsolidatedLog[],
  anchor: number | undefined
): string {
  if (consolidatedLogs.length === 0) {
    return `### Console Logs\n\nNo console logs captured.\n\n`
  }

  let output = `### Console Logs\n\n`
  output += `| First Seen | Last Seen | Level | Count | Message |\n`
  output += `|------------|-----------|-------|-------|---------|\n`
  const shouldTruncate = data.truncateConsoleLogs ?? true
  consolidatedLogs.forEach((log) => {
    output += `${formatConsoleLog(log, shouldTruncate, anchor)}\n`
  })
  output += '\n'
  return output
}

function formatNetworkSection(data: ExportData, anchor: number | undefined): string {
  if (data.networkEntries.length === 0) {
    return `### Network Requests\n\nNo network requests captured.\n\n`
  }

  const responseBodyMode = data.responseBodyMode ?? 'smart'
  const elevatedUrlPaths = computeElevatedUrlPaths(data.consoleLogs, data.networkEntries)

  const formatOptionsBase = {
    includeResponseBodies: data.includeResponseBodies ?? false,
    responseBodyMode,
    elevatedUrlPaths,
  }

  let output = `### Network Requests\n\n`
  if (data.deduplicateApiCalls) {
    const consolidated = consolidateNetworkEntries(data.networkEntries)
    output += `- **Unique Routes**: ${consolidated.length} (from ${data.networkEntries.length} total)\n\n`
    output += formatNetworkSummaryTable(consolidated)
    consolidated.forEach((group, i) => {
      output += formatConsolidatedNetworkEntry(group, {
        ...formatOptionsBase,
        index: i + 1,
        anchor,
      })
      output += '---\n\n'
    })
  } else {
    output += formatNetworkSummaryTableFromEntries(data.networkEntries)
    data.networkEntries.forEach((entry, i) => {
      output += formatNetworkEntry(entry, {
        ...formatOptionsBase,
        index: i + 1,
        anchor,
      })
      output += '---\n\n'
    })
  }

  return output
}

/**
 * Renders the network summary table. The 1-based row index in column #1
 * matches the `### #N` prefix on the per-entry heading emitted below —
 * agents can jump from a summary row straight to the full entry.
 *
 * The `host + path` cell is normalized: protocol stripped, query string
 * collapsed to `?…` when non-empty, and path truncated to ~60 chars.
 * Consolidated groups suffix the cell with ` (×N)` for multiplicity.
 */
function formatNetworkSummaryTable(groups: ConsolidatedNetworkEntry[]): string {
  let output = `| # | method | host + path | status | dur | size |\n`
  output += `|---|--------|-------------|--------|-----|------|\n`
  groups.forEach((group, i) => {
    const first = group.entries[0]
    const hostPath = normalizeHostPath(first.request.url)
    const cell = group.count > 1 ? `${hostPath} (×${group.count})` : hostPath
    output += `| ${i + 1} | ${first.request.method} | ${cell} | ${first.response.status} | ${formatDurationCell(first.time)} | ${formatSizeCell(first.response?.content?.text?.length ?? 0)} |\n`
  })
  output += '\n'
  return output
}

function formatNetworkSummaryTableFromEntries(entries: HAREntry[]): string {
  let output = `| # | method | host + path | status | dur | size |\n`
  output += `|---|--------|-------------|--------|-----|------|\n`
  entries.forEach((entry, i) => {
    const hostPath = normalizeHostPath(entry.request.url)
    output += `| ${i + 1} | ${entry.request.method} | ${hostPath} | ${entry.response.status} | ${formatDurationCell(entry.time)} | ${formatSizeCell(entry.response?.content?.text?.length ?? 0)} |\n`
  })
  output += '\n'
  return output
}

function formatDurationCell(time: number | undefined): string {
  return time ? `${time}ms` : ''
}

function formatSizeCell(emittedBytes: number): string {
  return emittedBytes > 0 ? formatBytes(emittedBytes) : ''
}

/**
 * Normalizes a URL for the summary table: protocol stripped, query string
 * collapsed to `?…` when non-empty, and path truncated to ~60 chars with a
 * `…` ellipsis suffix when longer.
 */
function normalizeHostPath(url: string): string {
  const stripped = url.replace(/^https?:\/\//, '')
  const qIndex = stripped.indexOf('?')
  let hostPath: string
  if (qIndex >= 0) {
    const path = stripped.substring(0, qIndex)
    hostPath = `${path}?…`
  } else {
    hostPath = stripped
  }
  if (hostPath.length > 60) {
    return `${hostPath.substring(0, 60)}…`
  }
  return hostPath
}

function formatDebugSection(data: ExportData): string {
  if (!data.debugEntries || data.debugEntries.length === 0) {
    return ''
  }

  let output = `### Extension Debug Log\n\n`
  output += `| Timestamp | Source | Category | Message |\n`
  output += `|------------|--------|----------|---------|\n`
  for (const entry of data.debugEntries) {
    const time = new Date(entry.timestamp).toISOString().slice(11, 23)
    const message = String(entry.message).replace(/\|/g, '\\|')
    output += `| ${time} | ${entry.source} | ${entry.category} | ${message} |\n`
  }
  output += '\n'
  return output
}
