/**
 * Tests for utils/formatter.ts
 * Comprehensive test coverage for formatMarkdown() and formatBytes()
 */

import { describe, expect, test } from 'vitest'
import { type ExportData, formatBytes, formatMarkdown } from './formatter'

describe('formatBytes', () => {
  test('should format 0 bytes correctly', () => {
    expect(formatBytes(0)).toBe('0 B')
  })

  test('should format bytes less than 1KB', () => {
    expect(formatBytes(100)).toBe('100 B')
    expect(formatBytes(1023)).toBe('1023 B')
  })

  test('should format kilobytes', () => {
    expect(formatBytes(1024)).toBe('1 KB')
    expect(formatBytes(1536)).toBe('1.5 KB')
    expect(formatBytes(1023 * 1024 - 1)).toBe('1023 KB')
  })

  test('should format megabytes', () => {
    expect(formatBytes(1024 * 1024)).toBe('1 MB')
    expect(formatBytes(5 * 1024 * 1024)).toBe('5 MB')
    expect(formatBytes(2.5 * 1024 * 1024)).toBe('2.5 MB')
  })

  test('should format gigabytes', () => {
    expect(formatBytes(1024 * 1024 * 1024)).toBe('1 GB')
    expect(formatBytes(2.5 * 1024 * 1024 * 1024)).toBe('2.5 GB')
  })

  test('should format large values correctly', () => {
    expect(formatBytes(10 * 1024 * 1024 * 1024)).toBe('10 GB')
    expect(formatBytes(1023 * 1024 * 1024 * 1024)).toBe('1023 GB')
  })
})

describe('formatMarkdown - Environment Section', () => {
  test('should include environment section with URL and timestamp', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('## Debug Log Export')
    expect(result).toContain('### Environment')
    expect(result).toContain('- **URL**: https://example.com')
    expect(result).toContain('- **Timestamp**: 2024-01-15T10:30:00Z')
  })

  test('should include agent context section when enabled', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      includeAgentContext: true,
      consoleLogs: [],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('### LLM Guidance')
    expect(result).toContain('This output is generated by Loggy')
  })

  test('should omit agent context section when disabled', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      includeAgentContext: false,
      consoleLogs: [],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).not.toContain('### LLM Guidance')
  })

  test('should include counts in environment section', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [
        { timestamp: '10:30:00', level: 'error', message: 'Error' },
        { timestamp: '10:30:01', level: 'log', message: 'Log' },
        { timestamp: '10:30:02', level: 'warn', message: 'Warning' },
      ],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://api.example.com', method: 'GET' },
          response: { status: 200, statusText: 'OK' },
          time: 100,
        },
        {
          startedDateTime: '2024-01-15T10:30:01Z',
          request: { url: 'https://api.example.com/data', method: 'POST' },
          response: { status: 201, statusText: 'Created' },
          time: 150,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('- **Console Logs**: 3')
    expect(result).toContain('- **Unique Console Events**: 3')
    expect(result).toContain('- **Consolidated Repeats**: 0')
    expect(result).toContain('- **Network Requests**: 2')
  })

  test('should escape pipes in URL', () => {
    const data: ExportData = {
      url: 'https://example.com/path|with|pipes',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('- **URL**: https://example.com/path\\|with\\|pipes')
  })
})

describe('formatMarkdown - Console Logs Section', () => {
  test('should handle empty console logs array', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('### Console Logs')
    expect(result).toContain('No console logs captured')
  })

  test('should create table with console logs', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [
        { timestamp: '10:30:00', level: 'error', message: 'Something went wrong' },
        { timestamp: '10:30:01', level: 'log', message: 'Information' },
      ],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('### Console Logs')
    expect(result).toContain('| First Seen | Last Seen | Level | Count | Message |')
    expect(result).toContain('|------------|-----------|-------|-------|---------|')
    expect(result).toContain('| 10:30:00 | 10:30:00 | error | 1 | Something went wrong |')
    expect(result).toContain('| 10:30:01 | 10:30:01 | log | 1 | Information |')
  })

  test('should handle all log levels', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [
        { timestamp: '10:30:00', level: 'error', message: 'Error message' },
        { timestamp: '10:30:01', level: 'warn', message: 'Warning message' },
        { timestamp: '10:30:02', level: 'log', message: 'Log message' },
        { timestamp: '10:30:03', level: 'info', message: 'Info message' },
        { timestamp: '10:30:04', level: 'debug', message: 'Debug message' },
      ],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('| 10:30:00 | 10:30:00 | error | 1 | Error message |')
    expect(result).toContain('| 10:30:01 | 10:30:01 | warn | 1 | Warning message |')
    expect(result).toContain('| 10:30:02 | 10:30:02 | log | 1 | Log message |')
    expect(result).toContain('| 10:30:03 | 10:30:03 | info | 1 | Info message |')
    expect(result).toContain('| 10:30:04 | 10:30:04 | debug | 1 | Debug message |')
  })

  test('should consolidate repeated console logs into count and time range', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [
        { timestamp: '10:30:00', level: 'log', message: 'Repeated entry' },
        { timestamp: '10:30:01', level: 'log', message: 'Repeated entry' },
        { timestamp: '10:30:02', level: 'log', message: 'Repeated entry' },
      ],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('- **Console Logs**: 3')
    expect(result).toContain('- **Unique Console Events**: 1')
    expect(result).toContain('- **Consolidated Repeats**: 2')
    expect(result).toContain('| 10:30:00 | 10:30:02 | log | 3 | Repeated entry |')
  })

  test('should include debug signals summary', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [
        { timestamp: '10:30:00', level: 'warn', message: 'Potential issue' },
        { timestamp: '10:30:01', level: 'error', message: 'Unhandled exception occurred' },
      ],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('### Debug Signals')
    expect(result).toContain('- **Errors (raw/consolidated)**: 1/1')
    expect(result).toContain('- **Warnings (raw/consolidated)**: 1/1')
    expect(result).toContain('- **Failure-Likely Events**: 1')
    expect(result).toContain('- [error] (1x) 10:30:01 - Unhandled exception occurred')
  })

  test('should compute first and last timestamps even for out-of-order logs', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [
        { timestamp: '10:30:05', level: 'log', message: 'Out of order entry' },
        { timestamp: '10:30:01', level: 'log', message: 'Out of order entry' },
        { timestamp: '10:30:03', level: 'log', message: 'Out of order entry' },
      ],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('| 10:30:01 | 10:30:05 | log | 3 | Out of order entry |')
  })

  test('should treat warning as failure signal only when warning is failure-like', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [
        { timestamp: '10:30:00', level: 'warn', message: 'Smooth scroll may be less precise' },
        { timestamp: '10:30:01', level: 'warn', message: 'Request failed with status 500' },
      ],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('- **Failure-Likely Events**: 1')
    expect(result).toContain('- [warn] (1x) 10:30:01 - Request failed with status 500')
  })

  test('should escape markdown special characters in messages', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [
        { timestamp: '10:30:00', level: 'error', message: 'Text with | pipes |' },
        { timestamp: '10:30:01', level: 'log', message: 'Text with `backticks`' },
        { timestamp: '10:30:02', level: 'warn', message: 'Text with *asterisks*' },
      ],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('Text with \\| pipes \\|')
    expect(result).toContain('Text with \\`backticks\\`')
    expect(result).toContain('Text with \\*asterisks\\*')
  })

  test('should truncate long messages', () => {
    const longMessage = 'A'.repeat(400)
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [{ timestamp: '10:30:00', level: 'log', message: longMessage }],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('... [truncated]')
    expect(result).not.toContain(longMessage)
  })

  test('should NOT truncate console logs when truncateConsoleLogs is false', () => {
    const longMessage = 'A'.repeat(400)
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [{ timestamp: '10:30:00', level: 'log', message: longMessage }],
      networkEntries: [],
      truncateConsoleLogs: false,
    }

    const result = formatMarkdown(data)

    expect(result).not.toContain('... [truncated]')
    expect(result).toContain(longMessage)
  })

  test('should NOT truncate debug signals when truncateConsoleLogs is false', () => {
    const longMessage = 'A'.repeat(400)
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [{ timestamp: '10:30:00', level: 'error', message: longMessage }],
      networkEntries: [],
      truncateConsoleLogs: false,
    }

    const result = formatMarkdown(data)

    expect(result).not.toContain('... [truncated]')
    expect(result).toContain(longMessage)
  })

  test('should truncate console logs when truncateConsoleLogs is true', () => {
    const longMessage = 'A'.repeat(400)
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [{ timestamp: '10:30:00', level: 'log', message: longMessage }],
      networkEntries: [],
      truncateConsoleLogs: true,
    }

    const result = formatMarkdown(data)

    expect(result).toContain('... [truncated]')
    expect(result).not.toContain(longMessage)
  })

  test('should truncate console logs when truncateConsoleLogs is undefined (default behavior)', () => {
    const longMessage = 'A'.repeat(400)
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [{ timestamp: '10:30:00', level: 'log', message: longMessage }],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('... [truncated]')
    expect(result).not.toContain(longMessage)
  })
})

describe('formatMarkdown - Network Requests Section', () => {
  test('should handle empty network entries array', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('### Network Requests')
    expect(result).toContain('No network requests captured')
  })

  test('should format network entries with basic details', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://api.example.com/data', method: 'GET' },
          response: { status: 200, statusText: 'OK' },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('### Network Requests')
    expect(result).toContain('### GET https://api.example.com/data')
    expect(result).toContain('- **Time**: 2024-01-15T10:30:00Z')
    expect(result).toContain('- **Duration**: 100ms')
    expect(result).toContain('- **Status**: 200 OK')
  })

  test('should escape pipes in URL and method', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://api.example.com|test', method: 'GET|CUSTOM' },
          response: { status: 200, statusText: 'OK' },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('### GET\\|CUSTOM https://api.example.com\\|test')
  })

  test('should format request headers', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: {
            url: 'https://api.example.com/data',
            method: 'GET',
            headers: [
              { name: 'Content-Type', value: 'application/json' },
              { name: 'Authorization', value: 'Bearer token123' },
            ],
          },
          response: { status: 200, statusText: 'OK' },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('#### Request Headers')
    expect(result).toContain('```')
    expect(result).toContain('  Content-Type: application/json')
    expect(result).toContain('  Authorization: Bearer token123')
  })

  test('should handle missing request headers', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: {
            url: 'https://api.example.com/data',
            method: 'GET',
          },
          response: { status: 200, statusText: 'OK' },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('#### Request Headers')
    expect(result).toContain('```')
    expect(result).toContain('None')
  })

  test('should format request body with code block for JSON', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: {
            url: 'https://api.example.com/data',
            method: 'POST',
            postData: {
              mimeType: 'application/json',
              text: '{"key":"value"}',
            },
          },
          response: { status: 200, statusText: 'OK' },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('#### Request Body')
    expect(result).toContain('```json')
    expect(result).toContain('{"key":"value"}')
  })

  test('should escape markdown in request body', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: {
            url: 'https://api.example.com/data',
            method: 'POST',
            postData: {
              mimeType: 'application/json',
              text: 'text with | pipes',
            },
          },
          response: { status: 200, statusText: 'OK' },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('text with \\| pipes')
  })

  test('should format response headers', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://api.example.com/data', method: 'GET' },
          response: {
            status: 200,
            statusText: 'OK',
            headers: [
              { name: 'Content-Type', value: 'application/json' },
              { name: 'Content-Length', value: '123' },
            ],
          },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('#### Response Headers')
    expect(result).toContain('```')
    expect(result).toContain('  Content-Type: application/json')
    expect(result).toContain('  Content-Length: 123')
  })

  test('should format response content with code block for JSON', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      includeResponseBodies: true,
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://api.example.com/data', method: 'GET' },
          response: {
            status: 200,
            statusText: 'OK',
            content: {
              size: 1024,
              mimeType: 'application/json',
              text: '{"result":"success"}',
            },
          },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('#### Response Content')
    expect(result).toContain('```json')
    expect(result).toContain('{"result":"success"}')
    expect(result).toContain('- **Size**: 1 KB')
    expect(result).toContain('- **MIME Type**: application/json')
  })

  test('should format response content with code block for HTML', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      includeResponseBodies: true,
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://example.com/page', method: 'GET' },
          response: {
            status: 200,
            statusText: 'OK',
            content: {
              size: 2048,
              mimeType: 'text/html',
              text: '<html><body>Hello</body></html>',
            },
          },
          time: 150,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('#### Response Content')
    expect(result).toContain('```html')
    expect(result).toContain('<html><body>Hello</body></html>')
  })

  test('should handle missing response content', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://api.example.com/data', method: 'GET' },
          response: {
            status: 200,
            statusText: 'OK',
          },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('- **Size**: N/A')
    expect(result).toContain('- **MIME Type**: unknown')
    expect(result).not.toContain('#### Response Content')
  })

  test('should handle missing duration', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://api.example.com/data', method: 'GET' },
          response: { status: 200, statusText: 'OK' },
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('- **Duration**: N/A')
  })

  test('should format code block for JavaScript MIME type', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      includeResponseBodies: true,
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://example.com/script.js', method: 'GET' },
          response: {
            status: 200,
            statusText: 'OK',
            content: {
              size: 512,
              mimeType: 'application/javascript',
              text: 'console.log("test");',
            },
          },
          time: 50,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('```javascript')
    expect(result).toContain('console.log("test");')
  })

  test('should format code block for CSS MIME type', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      includeResponseBodies: true,
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://example.com/style.css', method: 'GET' },
          response: {
            status: 200,
            statusText: 'OK',
            content: {
              size: 256,
              mimeType: 'text/css',
              text: 'body { color: red; }',
            },
          },
          time: 30,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('```css')
    expect(result).toContain('body { color: red; }')
  })

  test('should not create code block for binary MIME types', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://example.com/image.png', method: 'GET' },
          response: {
            status: 200,
            statusText: 'OK',
            content: {
              size: 10240,
              mimeType: 'image/png',
            },
          },
          time: 75,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).not.toContain('#### Response Content')
    expect(result).toContain('- **Size**: 10 KB')
    expect(result).toContain('- **MIME Type**: image/png')
  })

  test('should add separator between network entries', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://api.example.com/data1', method: 'GET' },
          response: { status: 200, statusText: 'OK' },
          time: 100,
        },
        {
          startedDateTime: '2024-01-15T10:30:01Z',
          request: { url: 'https://api.example.com/data2', method: 'GET' },
          response: { status: 200, statusText: 'OK' },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('---')
  })
})

describe('formatMarkdown - Integration', () => {
  test('should generate complete markdown with both console and network data', () => {
    const data: ExportData = {
      url: 'https://example.com',
      timestamp: '2024-01-15T10:30:00Z',
      consoleLogs: [
        { timestamp: '10:30:00', level: 'error', message: 'Test error' },
        { timestamp: '10:30:01', level: 'log', message: 'Test log' },
      ],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: { url: 'https://api.example.com/data', method: 'GET' },
          response: { status: 200, statusText: 'OK' },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    expect(result).toContain('## Debug Log Export')
    expect(result).toContain('### Environment')
    expect(result).toContain('### Debug Signals')
    expect(result).toContain('### Console Logs')
    expect(result).toContain('### Network Requests')
    expect(result).toContain('| First Seen | Last Seen | Level | Count | Message |')
    expect(result).toContain('### GET https://api.example.com/data')
  })

  test('should handle markdown escaping throughout entire output', () => {
    const data: ExportData = {
      url: 'https://example.com|test',
      timestamp: '2024-01-15T10:30:00Z',
      includeResponseBodies: true,
      consoleLogs: [{ timestamp: '10:30:00', level: 'log', message: 'Message with *asterisks*' }],
      networkEntries: [
        {
          startedDateTime: '2024-01-15T10:30:00Z',
          request: {
            url: 'https://api.example.com/data|test',
            method: 'POST|TEST',
            headers: [{ name: 'X-Custom|Header', value: 'value|1' }],
            postData: {
              mimeType: 'application/json',
              text: '{"key":"value|with|pipes"}',
            },
          },
          response: {
            status: 200,
            statusText: 'OK',
            headers: [{ name: 'X-Response|Header', value: 'response|value' }],
            content: {
              size: 512,
              mimeType: 'application/json',
              text: '{"result":"ok|data"}',
            },
          },
          time: 100,
        },
      ],
    }

    const result = formatMarkdown(data)

    // URL and method
    expect(result).toContain('POST\\|TEST https://api.example.com/data\\|test')
    expect(result).toContain('example.com\\|test')

    // Console log
    expect(result).toContain('Message with \\*asterisks\\*')

    // Request headers
    expect(result).toContain('X-Custom\\|Header: value\\|1')

    // Request body
    expect(result).toContain('value\\|with\\|pipes')

    // Response headers
    expect(result).toContain('X-Response\\|Header: response\\|value')

    // Response content
    expect(result).toContain('ok\\|data')
  })
})

describe('formatMarkdown - Token-efficient Contract', () => {
  describe('Canonical failure ranking', () => {
    test('should rank errors before warnings in Debug Signals section', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          { timestamp: '10:30:01', level: 'warn', message: 'Warning failed with status 500' },
          { timestamp: '10:30:00', level: 'error', message: 'Error message' },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      // Error should appear before warning in Debug Signals
      const errorPos = result.indexOf('[error]')
      const warnPos = result.lastIndexOf('[warn]')
      expect(errorPos).toBeGreaterThanOrEqual(0)
      expect(warnPos).toBeGreaterThanOrEqual(0)
      expect(errorPos).toBeLessThan(warnPos)
    })

    test('should rank failure-like warnings above benign warnings', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          { timestamp: '10:30:00', level: 'warn', message: 'Smooth scroll may be less precise' },
          { timestamp: '10:30:01', level: 'warn', message: 'Request failed with status 500' },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      // Failure-like warning (500 status) should appear first
      const benignPos = result.indexOf('Smooth scroll may be less precise')
      const failurePos = result.indexOf('Request failed with status 500')
      expect(benignPos).toBeGreaterThanOrEqual(0)
      expect(failurePos).toBeGreaterThanOrEqual(0)
      expect(failurePos).toBeLessThan(benignPos)
    })

    test('should rank repeated failures by count (descending)', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          { timestamp: '10:30:00', level: 'error', message: 'First error' },
          { timestamp: '10:30:00', level: 'error', message: 'First error' },
          { timestamp: '10:30:01', level: 'error', message: 'Second error' },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      // First error (2x) should appear before second error (1x)
      const firstPos = result.indexOf('First error')
      const secondPos = result.indexOf('Second error')
      expect(firstPos).toBeGreaterThanOrEqual(0)
      expect(secondPos).toBeGreaterThanOrEqual(0)
      expect(firstPos).toBeLessThan(secondPos)
    })
  })

  describe('Representative serialization', () => {
    test('should serialize TypeError with name and message in export', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          {
            timestamp: '10:30:00',
            level: 'error',
            message: "TypeError: Cannot read properties of undefined (reading 'id')",
          },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain("TypeError: Cannot read properties of undefined (reading 'id')")
      expect(result).toContain('[error]')
    })

    test('should serialize circular objects with a [Circular] marker', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          { timestamp: '10:30:00', level: 'log', message: '{name: "root", self: [Circular]}' },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('{name: "root", self: [Circular]}')
    })

    test('should serialize arrays with proper JSON format', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          { timestamp: '10:30:00', level: 'log', message: '[1, 2, {nested: "value"}]' },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('[1, 2, {nested: "value"}]')
    })

    test('should serialize DOM-like objects with key properties', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          {
            timestamp: '10:30:00',
            level: 'log',
            message: '<div#app.container>',
          },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('<div#app.container>')
    })

    test('should serialize undefined as string "undefined"', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [{ timestamp: '10:30:00', level: 'log', message: 'undefined' }],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('undefined')
    })

    test('should serialize null as string "null"', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [{ timestamp: '10:30:00', level: 'log', message: 'null' }],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('null')
    })

    test('should serialize BigInt/Symbol as semantic strings', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          { timestamp: '10:30:00', level: 'log', message: '9007199254740991n Symbol(test)' },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('9007199254740991n Symbol(test)')
    })
  })

  describe('Repeated-event consolidation', () => {
    test('should consolidate identical console logs into single row with count', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          { timestamp: '10:30:00', level: 'log', message: 'Repeated message' },
          { timestamp: '10:30:01', level: 'log', message: 'Repeated message' },
          { timestamp: '10:30:02', level: 'log', message: 'Repeated message' },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      // Should show consolidated count
      expect(result).toContain('**Console Logs**: 3')
      expect(result).toContain('**Unique Console Events**: 1')
      expect(result).toContain('**Consolidated Repeats**: 2')
      expect(result).toContain('| 3 |')
    })

    test('should compute first and last timestamps for consolidated logs', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          { timestamp: '10:30:05', level: 'log', message: 'Repeated message' },
          { timestamp: '10:30:01', level: 'log', message: 'Repeated message' },
          { timestamp: '10:30:03', level: 'log', message: 'Repeated message' },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      // Should show time range from earliest to latest
      expect(result).toContain('10:30:01')
      expect(result).toContain('10:30:05')
    })

    test('should consolidate repeated errors and include in Debug Signals', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          {
            timestamp: '10:30:00',
            level: 'error',
            message: 'TypeError: Cannot read properties of undefined',
          },
          {
            timestamp: '10:30:01',
            level: 'error',
            message: 'TypeError: Cannot read properties of undefined',
          },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('[error] (2x)')
      expect(result).toContain('TypeError: Cannot read properties of undefined')
    })

    test('should not consolidate different error messages', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          {
            timestamp: '10:30:00',
            level: 'error',
            message: 'TypeError: Cannot read properties of undefined',
          },
          {
            timestamp: '10:30:01',
            level: 'error',
            message: 'ReferenceError: variable is not defined',
          },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('**Unique Console Events**: 2')
      expect(result).toContain('TypeError: Cannot read properties of undefined')
      expect(result).toContain('ReferenceError: variable is not defined')
    })
  })

  describe('Failure signal detection', () => {
    test('should detect error keywords in warnings as failure signals', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [{ timestamp: '10:30:00', level: 'warn', message: 'warning: error detected' }],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('**Failure-Likely Events**: 1')
      expect(result).toContain('[warn] (1x)')
    })

    test('should detect fail keyword in warnings as failure signals', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [{ timestamp: '10:30:00', level: 'warn', message: 'warning: request failed' }],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('**Failure-Likely Events**: 1')
      expect(result).toContain('[warn] (1x)')
    })

    test('should detect HTTP 4xx/5xx status codes as failure signals', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          { timestamp: '10:30:00', level: 'warn', message: 'API returned 404 not found' },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('**Failure-Likely Events**: 1')
      expect(result).toContain('[warn] (1x)')
    })

    test('should detect TypeError in warnings as failure signal', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          { timestamp: '10:30:00', level: 'warn', message: 'caught typeerror in promise' },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('**Failure-Likely Events**: 1')
    })

    test('should detect ReferenceError in warnings as failure signal', () => {
      const data: ExportData = {
        url: 'https://example.com',
        timestamp: '2024-01-15T10:30:00Z',
        consoleLogs: [
          { timestamp: '10:30:00', level: 'warn', message: 'caught referenceerror in try-catch' },
        ],
        networkEntries: [],
      }

      const result = formatMarkdown(data)

      expect(result).toContain('**Failure-Likely Events**: 1')
    })
  })
})
