/**
 * Markdown Formatter for Loggy Chrome Extension
 * Exports captured console and network data as structured Markdown
 */

import type { ConsoleMessage } from '../types/console'
import type { HAREntry } from '../types/har'
import type { ConsolidatedLog } from './consolidation'
import { consolidateNetworkEntries } from './consolidation-network'
import type { DebugEntry } from './debug-logger'
import {
  bySeverityThenCount,
  consolidateConsoleLogs,
  formatConsoleLog,
  formatTimestampRange,
  isLikelyFailureSignal,
} from './formatter-console'
import { formatConsolidatedNetworkEntry, formatNetworkEntry } from './formatter-network'
import { escapeMarkdown, formatBytes, truncate } from './formatter-strings'

/**
 * Complete export data structure for Markdown generation
 */
export interface ExportData {
  /** URL of the inspected page */
  url: string
  /** ISO 8601 timestamp of capture */
  timestamp: string
  /** Whether to include context for coding agents/LLMs */
  includeAgentContext?: boolean
  /** Whether to include response body content in network entries */
  includeResponseBodies?: boolean
  /** Whether to truncate console log messages (default: true) */
  truncateConsoleLogs?: boolean
  /** Whether to deduplicate identical API calls in the export */
  deduplicateApiCalls?: boolean
  /** Captured console messages */
  consoleLogs: ConsoleMessage[]
  /** Captured network HAR entries */
  networkEntries: HAREntry[]
  /** Optional debug log entries (only present in debug builds) */
  debugEntries?: DebugEntry[]
}

export { formatBytes, truncate }

/**
 * Formats complete export data as structured Markdown document
 * @param data - Export data containing console logs and network entries
 * @returns Formatted Markdown string
 */
export function formatMarkdown(data: ExportData): string {
  const consolidatedLogs = consolidateConsoleLogs(data.consoleLogs).sort(bySeverityThenCount)
  const repeatedLogCount = data.consoleLogs.length - consolidatedLogs.length
  const failureSignals = consolidatedLogs.filter(isLikelyFailureSignal).slice(0, 10)
  const levelCount = data.consoleLogs.reduce(
    (acc, log) => {
      acc[log.level] += 1
      return acc
    },
    { error: 0, warn: 0, log: 0, info: 0, debug: 0 } as Record<ConsoleMessage['level'], number>
  )
  const consolidatedLevelCount = consolidatedLogs.reduce(
    (acc, log) => {
      acc[log.level] += 1
      return acc
    },
    { error: 0, warn: 0, log: 0, info: 0, debug: 0 } as Record<ConsoleMessage['level'], number>
  )

  return (
    formatHeaderSection(data) +
    formatEnvironmentSection(data, consolidatedLogs.length, repeatedLogCount) +
    formatDebugSignalsSection(data, failureSignals, levelCount, consolidatedLevelCount) +
    formatConsoleSection(data, consolidatedLogs) +
    formatNetworkSection(data) +
    formatDebugSection(data)
  )
}

function formatHeaderSection(data: ExportData): string {
  let output = `## Debug Log Export\n\n`
  if (data.includeAgentContext) {
    output += `### LLM Guidance\n\n`
    output += `- This output is generated by Loggy, a Chrome DevTools extension for debugging web pages.\n`
    output += `- It captures browser console events and network requests from the inspected tab.\n`
    output += `- Start with **Debug Signals**, then correlate with **Console Logs** and **Network Requests** to find root causes.\n`
    output += `- Use URL, timestamps, and request metadata to map issues to failing user flows.\n\n`
  }
  return output
}

function formatEnvironmentSection(
  data: ExportData,
  uniqueCount: number,
  repeatedCount: number
): string {
  let output = `### Environment\n\n`
  output += `- **URL**: ${escapeMarkdown(data.url)}\n`
  output += `- **Timestamp**: ${data.timestamp}\n`
  output += `- **Console Logs**: ${data.consoleLogs.length}\n`
  output += `- **Unique Console Events**: ${uniqueCount}\n`
  output += `- **Consolidated Repeats**: ${repeatedCount}\n`
  output += `- **Network Requests**: ${data.networkEntries.length}\n\n`
  return output
}

function formatDebugSignalsSection(
  data: ExportData,
  failureSignals: ConsolidatedLog[],
  levelCount: Record<ConsoleMessage['level'], number>,
  consolidatedLevelCount: Record<ConsoleMessage['level'], number>
): string {
  let output = `### Debug Signals\n\n`
  output += `- **Errors (raw/consolidated)**: ${levelCount.error}/${consolidatedLevelCount.error}\n`
  output += `- **Warnings (raw/consolidated)**: ${levelCount.warn}/${consolidatedLevelCount.warn}\n`
  output += `- **Failure-Likely Events**: ${failureSignals.length}\n\n`

  if (failureSignals.length > 0) {
    const shouldTruncate = data.truncateConsoleLogs ?? true
    failureSignals.forEach((signal) => {
      const message = shouldTruncate ? truncate(signal.message, 320) : signal.message
      output += `- [${signal.level}] (${signal.count}x) ${formatTimestampRange(signal)} - ${escapeMarkdown(message)}\n`
    })
    output += '\n'
  }

  return output
}

function formatConsoleSection(data: ExportData, consolidatedLogs: ConsolidatedLog[]): string {
  if (consolidatedLogs.length === 0) {
    return `### Console Logs\n\nNo console logs captured.\n\n`
  }

  let output = `### Console Logs\n\n`
  output += `| First Seen | Last Seen | Level | Count | Message |\n`
  output += `|------------|-----------|-------|-------|---------|\n`
  const shouldTruncate = data.truncateConsoleLogs ?? true
  consolidatedLogs.forEach((log) => {
    output += `${formatConsoleLog(log, shouldTruncate)}\n`
  })
  output += '\n'
  return output
}

function formatNetworkSection(data: ExportData): string {
  if (data.networkEntries.length === 0) {
    return `### Network Requests\n\nNo network requests captured.\n\n`
  }

  let output = ''
  if (data.deduplicateApiCalls) {
    const consolidated = consolidateNetworkEntries(data.networkEntries)
    output += `### Network Requests\n\n`
    output += `- **Unique Routes**: ${consolidated.length} (from ${data.networkEntries.length} total)\n\n`
    consolidated.forEach((group) => {
      output += formatConsolidatedNetworkEntry(group, {
        includeResponseBodies: data.includeResponseBodies ?? false,
      })
      output += '---\n\n'
    })
  } else {
    output += `### Network Requests\n\n`
    data.networkEntries.forEach((entry) => {
      output += formatNetworkEntry(entry, {
        includeResponseBodies: data.includeResponseBodies ?? false,
      })
      output += '---\n\n'
    })
  }

  return output
}

function formatDebugSection(data: ExportData): string {
  if (!data.debugEntries || data.debugEntries.length === 0) {
    return ''
  }

  let output = `### Extension Debug Log\n\n`
  output += `| Timestamp | Source | Category | Message |\n`
  output += `|------------|--------|----------|---------|\n`
  for (const entry of data.debugEntries) {
    const time = new Date(entry.timestamp).toISOString().slice(11, 23)
    const message = String(entry.message).replace(/\|/g, '\\|')
    output += `| ${time} | ${entry.source} | ${entry.category} | ${message} |\n`
  }
  output += '\n'
  return output
}
